services:
  app:
    image: node:16-alpine
    command: sh -c "yarn install && yarn run dev"
    ports:
      - 3000:3000
    working_dir: /projet-programmation-web
    volumes:
      - ./:/projet-programmation-web
