services:
  db:
    build:
      context: .
      dockerfile: DB-Dockerfile
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5438:5432"
    volumes:
      - db:/var/lib/postgresql/data
  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: sh -c "yarn install && yarn run dev"
    working_dir: /projet-programmation-web
    ports:
      - 3000:3000
    volumes:
      - ./:/projet-programmation-web
    depends_on:
      - db
    links:
      - db
    environment:
      DATABASE_URL: "postgresql://postgres:postgres@db:5432/postgres?schema=public"
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: postgres
      GRAFBASE_API_URL: "http://127.0.0.1:3000/api/graphql"
      API_PORT: 3000
  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4:5.5
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: secret
      PGADMIN_LISTEN_PORT: 80
    ports:
      - "8080:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
volumes:
  db:
    driver: local
  pgadmin-data:
